# Generated by Django 6.0 on 2025-12-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('overall_rating', models.CharField(max_length=50, verbose_name='Общая оценка')),
                ('liked_features', models.TextField(blank=True, verbose_name='Что понравилось')),
                ('visit_frequency', models.CharField(max_length=50, verbose_name='Частота посещений')),
                ('recommendation', models.IntegerField(verbose_name='Рекомендация (0-10)')),
                ('suggestions', models.TextField(blank=True, verbose_name='Предложения')),
                ('agree_to_terms', models.BooleanField(verbose_name='Согласие на обработку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Сувенир',
                'verbose_name_plural': 'Сувениры',
            },
        ),
    ]
