# Generated by Django 6.0 on 2025-12-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для статьи (рекомендуемый размер: 1200x600)', null=True, upload_to='blog_images/', verbose_name='Изображение статьи'),
        ),
    ]
